### ISSUE TITLE
Convert the readme from rst to markdown

### ISSUE THREAD

**Issue by ocefpaf** [iobis/pyobis#103]
@ayushanand18 is that something you want to do? Markdown is easier to maintain, read, and render pretty much anywhere. We will need to adjust the [metadata here](https://github.com/iobis/pyobis/blob/main/setup.cfg#L7) too.

**Comment by ayushanand18** [comment]
I agree

> @ayushanand18 is that something you want to do? 

Yes, sure!
> Markdown is easier to maintain, read, and render pretty much anywhere. We will need to adjust the [metadata here](https://github.com/iobis/pyobis/blob/main/setup.cfg#L7) too.

I agree MD is easy to maintain. I'll initiate a PR for this change.
