### ISSUE TITLE
GSoC meeting planning & agenda

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#13]
In June we will begin a set of weekly meetings to work on a project supported by Google Summer of Code. This issue is here to discuss plans for the first of these meetings. Expected attendees include me (Tylar Murray), Matt (@MathewBiddle), and Ayush (@ayushanand18). Let's discuss scheduling on the slack #gsoc_pyobis channel.

## agenda
* introductions
    * what you are hoping to get out of involvement in this project
* discuss TDD as described [in the workflow 1-pager](https://google.github.io/gsocguides/mentor/workflow) 
* begin working on strategic plan as described in the [management 1-pager](https://google.github.io/gsocguides/mentor/managing-the-plan)
* set up todo items before next meeting

**Comment by 7yl4r** [comment]
I am posting this here for now, but future notes will be kept in a separate repository.

## intros

* Tylar
    * PostDoc Software Engineer
    * University of South Florida IMaRS
    * Remote Sensing + Biodiversity Assessment
* Matt
    * self-taught python
    * physical oceanography background
    * wants to build out more example notebooks in [IOOS CodeLab](https://ioos.github.io/ioos_code_lab/content/intro.html)
    * lots of data managment experience
    * lots going on with annual DMAC meeting this week
    * Felipe will present on GSoC & introduce mentees
* Ayush
    * passionate about climate science
    * 1st year student
    * pythonista
    * worked on pyobis previously

## plans
* get tests working in GH-actions
    * PR ready to submit
* Tylar - get admin access?
* Ayush - create repo for 
     * initial proposal
     * high-level design document : markdown file(s) w/ checklist
     * meeting notes
     * Working hours: 16:00 - 19:00 hours IST
* Tylar - create project board & milestones
* Tylar - review pyobis

## new issues from proposal:
* [x] Update pyobis to use the new API
    * [x] Merge in URL changes done on the forks
* [ ] Make MoF response more efficient
    * returns list of dataframes so it's more usable
    * currently nested table each occurrence has nested measurment or fact
    * some trick to use pandas to pull out the nested part (`json.normalize`?)
* [ ] Create tutorial usage of each module
* [ ] Clarify listing of GBIF instead of OBIS in package description ref ([ref](https://github.com/iobis/pyobis/blob/master/setup.py#L25))
    * add link to pyGBIF?
    * use a notebook leveraging both pyGBIF & pyOBIS?
* [x] Increase test coverage
* [ ] Use CI push to PyPI
    * discussed w/ Felipe : used to do it w/ Travis CI, need to switch to gh-actions
* Create a Jupyter notebooks
    * what are "use cases" for each notebook?
        * search for relevant papers using OBIS|GBIF data & reproduce results in jupyter
        * [ ] see how species are moving downwards due to climate change.
            * search MoF for depth measurements & report on % that have it.
            * [relevant paper](https://doi.org/10.1111/geb.13414)
        * [ ] see how species are shifting north/south due to climate change.
    * can potentially publish notebooks to [JOSS](https://joss.theoj.org/)
* [ ] create CONTRIBUTING.md
* [ ] pyobis.visualize
    * create separate repo?
        * keeps pyobis dependencies light
        * makes viz libarary potentially usable w/ GBIF & other DwC data 
* [ ] look into [coveralls coverage](https://coveralls.io/github/sckott/pyobis?branch=master)
    * does it work w/ gh-actions?
    * is coverage 62%? if so: how to make it 100%?
    * maybe it just needs the badges changed

**Comment by ocefpaf** [comment]
> Use CI push to PyPI
> * discussed w/ Felipe : used to do it w/ Travis CI, need to switch to gh-actions

This can be the last thing we do for GSoC b/c we want to publish a working package. When the time comes we can pretty much copy-and-paste this GHA: https://github.com/ioos/ioos-python-package-skeleton/blob/main/.github/workflows/pypi.yml
