### ISSUE TITLE
Create `usage_guide.ipynb` & `occurrences_ocean_sunfish.ipynb` notebooks

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#15]
Should the tutorial be something added to the readme or a jupyter notebook?

**Comment by ayushanand18** [comment]
I think we can build a jupyter notebook that serves as a manual which is comprehensive (yet concise). We can add some examples to the README (like they are already) and explain a bit more about input params, and sample output in the Jupyter Notebook. To keep pyobis light, we can add a link to the notebook in the README itself. How does that sound?

**Comment by 7yl4r** [comment]
Yes, I think that sounds like a good way to go. 👍

**Comment by ocefpaf** [comment]
We can use the notebooks to build docs. Ideally we should have the documentation code in a single place to avoid spreading outdated code. For example, we update the API, we run the notebooks as part of the tests so we have to update the notebooks, the docs are auto-generated from the notebooks, all good right? But we usually forget the README :-/

I'd rather just have a link to the docs in the README to avoid that situation.

**Comment by ayushanand18** [comment]
I experimented creating a notebook for example usage + sample input and output, here's the [link](https://colab.research.google.com/drive/1z5YE1R10UyD0IN9dZovDzrf-_4AT60Xe?usp=sharing). Additionally, what we can't include in README to keep it concise we can include that in a new [EXAMPLES.md](https://github.com/ayushanand18/pyobis/blob/gsoc2022-working-aa/EXAMPLES.md) perhaps like this one, and including a badge to open in colab directly.

**Comment by 7yl4r** [comment]
This looks like a good start to me. I didn't know g-colab could open and run code from .md files; that's interesting. 

I don't know how to generate docs from notebooks like @ocefpaf suggests. @ocefpaf : can you link us to an example repo that does things the way you recommend? I need to do some reading about the various documentation-building toolings, and would like to know your recommendations.

**Comment by ayushanand18** [comment]
Actually, what I did was simply copying and pasting everything from Google colab I created, into MD.  I too don't know if there's way to generate .ipynb notebooks from markdown. I just included the badge to the notebook in the EXAMPLES.MD

**Comment by ocefpaf** [comment]
> However: I don't know how to generate docs from notebooks like @ocefpaf suggests. @ocefpaf : can you link us to an example repo that does things the way you recommend?

Sure. [This is a GitHub action (GHA)](https://github.com/ioos/ioos-python-package-skeleton/blob/main/.github/workflows/deploy-docs.yml) that does that. I like to add a notebooks folder where we keep the original ones, and they can also be linked to binder so users can try them online, and then run/convert them as part of the GHA, see https://github.com/ioos/ioos-python-package-skeleton/blob/d9f9f45eb41565d92dd1c7dd4691944e8b6cc6d4/.github/workflows/deploy-docs.yml#L38. That way the notebooks are also "tested" in the process of building the docs.

**Comment by 7yl4r** [comment]
[here is a work in progress on this](https://colab.research.google.com/drive/1z5YE1R10UyD0IN9dZovDzrf-_4AT60Xe?usp=sharing)

**Comment by 7yl4r** [comment]
* [ ] create /notebooks/
* [ ] add badge to open notebooks in google colab 
* [ ] put WiP `usage_guide.ipynb` notebook in `/notebooks/`
* [ ] add a note/link in readme so people know to look in /notebooks/ and specifically to start with `usage_guide.ipynb`
* [ ] create `/notebook/occurrences.ipynb` similar to [IOOS codelab robis example](https://ioos.github.io/ioos_code_lab/content/code_gallery/data_access_notebooks/2018-02-20-obis.html)
