### ISSUE TITLE
Use logging instead of print

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/pyobis#156]
Use the logging module instead of print so output can be silenced more easily.

**Comment by ayushanand18** [comment]
Thanks. I'll try my hands on this. 
Is there any use case people might be interested in writing the log output to a file? with a config variable maybe.

**Comment by pieterprovoost** [comment]
If we use the [logging](https://docs.python.org/3/library/logging.html) module then the user has the flexibility to specify logging level, format, and handlers (console, file, etc) for pyobis.
