### ISSUE TITLE
replace setup.py with setup.cfg|pyproject.toml

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#16]
* [ ] Clarify listing of GBIF instead of OBIS in package description ref ([ref](https://github.com/iobis/pyobis/blob/master/setup.py#L25))
    * add link to pyGBIF?
    * use a notebook leveraging both pyGBIF & pyOBIS?

Might be worth reviewing the rest of setup.py while you are in there.

**Comment by ayushanand18** [comment]
I would like to have some insights on the whole setup.py file, do we need to update the description field, update the URL field, Development Field or python versions.

**Comment by ayushanand18** [comment]
> How about notebook exemplifying the differences between pyGBIF & pyOBIS - or document that somewhere in the docs?

We can create some notebooks and couple them with the Jupyter Notebooks objective and try updating them to IOOS Code Lab.

**Comment by ocefpaf** [comment]
> I would like to have some insights on the whole setup.py file, do we need to update the description field, update the URL field, Development Field or python versions.

I would not worry about that right now. When the time comes I'd rather we have a more modern setup.cfg/pyproject.toml instead of a setup.py.
