### ISSUE TITLE
create 1st demo jupyter notebook

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#18]
* what are "use cases" for each notebook?
    * [x] outline different use-cases for pyobis
* search for relevant papers using OBIS|GBIF data & reproduce results in jupyter
* [ ] see how species are moving downwards due to climate change.
    * search MoF for depth measurements & report on % that have it.
    * [relevant paper](https://doi.org/10.1111/geb.13414)
* [ ] see how species are shifting north/south due to climate change.
* can potentially publish notebooks to [JOSS](https://joss.theoj.org/)
* we should also set up these notebooks to work with mybinder.org
* should the notebooks go in this repo or should we place them elsewhere?
    * [x] create a "notebooks" directory in the root dir
* [x] add [this notebook](https://colab.research.google.com/drive/1z5YE1R10UyD0IN9dZovDzrf-_4AT60Xe?usp=sharing)

----------

ongoing sunfish analysis in dev [on this branch](https://github.com/ayushanand18/pyobis/blob/sunfish/notebooks/occurrences_ocean_sunfish.ipynb)

**Comment by 7yl4r** [comment]
Current plan is to create a notebook similar to [this one from the IOOS code Lab](https://ioos.github.io/ioos_code_lab/content/code_gallery/data_access_notebooks/2018-02-20-obis.html), analyzing occurrences of sunfish specifically.

**Comment by ayushanand18** [comment]
I'm finding it hard to find occurrences records for sunfishes, out of the 6 I know I could barely get any occurrences records.

```
sunfishes = ['Lepomis cyanellus',
             'Mola mola',
             'Lepomis megalotis',
             'Acantharchus pomotis',
             'Lepomis gibbosus',
             'Lepomis auritus',
             'Lepomis microlophus',
]
for i in sunfishes:
  data = pd.DataFrame(occ.search(scientificname=i)['results'])
  if(len(data)>0):
    print("{} records for {}".format(len(data),data.scientificName[0]))
```

The output:

```
10 records for Mola mola
10 records for Lepomis gibbosus
```

**Comment by ayushanand18** [comment]
Maybe we need to look at some family that has been well covered.

**Comment by ayushanand18** [comment]
Also, while analyzing the data of some sea turtles I found some issues with the data quality. I found that `class` was missing for many occurrences records of *Chelonia mydas*, *Eretmochelys imbricata*, and *Lepidochelys olivacea* which perhaps is something unexpected. How do report it?

Data grabbed attached:
  | scientificName | scientificNameID | id | class
-- | -- | -- | -- | --
0|Chelonia mydas | urn:lsid:marinespecies.org:taxname:137206 | 00000156-9ccc-4eec-bb8c-54012aba7991 | NaN
2|Chelonia mydas | urn:lsid:marinespecies.org:taxname:137206 | 000073ef-42c6-47f5-947b-b933f30c0e83 | NaN
4|Chelonia mydas | urn:lsid:marinespecies.org:taxname:137206 | 000155e3-484b-4e44-bf70-3c6be43367e4 | NaN
5|Chelonia mydas | urn:lsid:marinespecies.org:taxname:137206 | 00019225-3ce3-4e6e-b97c-5bc306c55504 | NaN
6|Chelonia mydas | urn:lsid:marinespecies.org:taxname:137206 | 00019cfa-e5fb-46aa-a2c0-d84bdf651650 | NaN
7|Chelonia mydas | urn:lsid:marinespecies.org:taxname:137206 | 00029615-26c3-4649-83be-fd499f36f91a | NaN
8|Chelonia mydas | urn:lsid:marinespecies.org:taxname:137206 | 00040a9d-2f6f-4167-baf6-7369f54fc4b5 | NaN
9|Chelonia mydas | urn:lsid:marinespecies.org:taxname:137206 | 00046eff-a0bd-40ab-98ee-1671129fe48b | NaN

**Comment by MathewBiddle** [comment]
@albenson-usgs, see the last comment. Is `class` an optional field rarely submitted to OBIS? 

This might be a case where we are limited with what is provided to OBIS.

**Comment by 7yl4r** [comment]
> I'm finding it hard to find occurrences records for sunfishes, out of the 6 I know I could barely get any occurrences records.

I think your usage of `hasextensions` excludes any occurrence records that do not have MeasurementOrFace extensions. I think the majority of records do not. Try removing that parameter.

**Comment by albenson-usgs** [comment]
> @albenson-usgs, see the last comment. Is `class` an optional field rarely submitted to OBIS?
> 
> This might be a case where we are limited with what is provided to OBIS.

I'm not quite sure how pyobis operates but I'm pretty sure `class` is filled in through the matching with WoRMS. Pieter Provoost is really the one to ask about this.

**Comment by pieterprovoost** [comment]
`class` is not supposed to be empty for quality controlled records, looking into it.

**Comment by pieterprovoost** [comment]
Sorry for the delay, this was caused by an incomplete sync with WoRMS, all Chelonia records should now be **super**class Reptilia.

**Comment by ocefpaf** [comment]
> Chelonia records should now be superclass Reptilia.

I bet @ayushanand18 never thought that was the kind of comment he would see in his PRs : 😁

**Comment by ayushanand18** [comment]
> Sorry for the delay, this was caused by an incomplete sync with WoRMS, all Chelonia records should now be **super**class Reptilia.

Thank you so much @pieterprovoost for the information! Is it true for *Eretmochelys imbricata* and *Lepidochelys olivacea* as well?

**Comment by ayushanand18** [comment]
> I bet @ayushanand18 never thought that was the kind of comment he would see in his PRs 😁

True, @ocefpaf! :) It seems it's time for me to get back to reading some more books 😊.

**Comment by pieterprovoost** [comment]
Yes, it's the same for all reptile species.

**Comment by ayushanand18** [comment]
> Yes, it's the same for all reptile species.

Noted. Thanks!
