### ISSUE TITLE
create visualization module (or separate package)

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#20]
* [ ] pyobis.visualize
    * create separate repo?
        * keeps pyobis dependencies light
        * makes viz libarary potentially usable w/ GBIF & other DwC data 

text from proposal:

Developing an umbrella module inside the pyobis package that can be used directly
by the users to visualize data through existing modules. For eg., we can build a
top-level module, say pyobis.visualize which ingests JSON data from say
pyobis.occurrence and visualizes it based on some parameters like scientificname,
basisOfRecords, etc.

**Comment by MathewBiddle** [comment]
So, my first thought is let's bring in `geopandas` to make some quick and dirty plots (`geoplot` is what I end up using for publication quality maps - handles projections and customizations much better). 

I get nervous about the dependencies that might require. Maybe a simple matplotlib/pandas histogram plotting would be alright here? 

FWIW I have a few example notebooks on how I've been using the OBIS API to this point:

- https://github.com/MathewBiddle/sandbox/blob/main/notebooks/IOOS_occurrences_in_OBIS.ipynb
- https://github.com/MathewBiddle/bio_ice/blob/main/create_map_from_OBIS_API.ipynb
- https://github.com/MathewBiddle/bio_ice/blob/main/Create_species_map_from_OBIS_API.ipynb - trying to recreate [this](https://bbest.github.io/obis-lat-time-fig/#map,_hist,_time-series_combined) figure in python. Could never get the axis scales to line up with the map projection scale.

**Comment by 7yl4r** [comment]
Let's put the heavier visualization & analysis code into https://github.com/marinebon/py-dwc-viz.

Dependencies installed|imported into notebooks is okay, but let's try to keep the direct dependencies in the setup files light.

**Comment by ayushanand18** [comment]
That sounds really good. I'll start creating subsequent analysis notebooks there (as I do believe with subsequent analysis we are going to dig deeper.)
