### ISSUE TITLE
Activate reviewnb for this repo

### ISSUE THREAD

**Issue by ocefpaf** [iobis/pyobis#28]
@7yl4r I don't have enough rights but maybe you do. Can you activate https://app.reviewnb.com/ for this repo? It will make reviewing PR with notebooks a bit easier.

**Comment by 7yl4r** [comment]
I was not able to approve it outright, but I have requested permissions from the iobis org. I think it is @pieterprovoost who needs to approve that.

**Comment by pieterprovoost** [comment]
Should be ok now?
