### ISSUE TITLE
add progress bar to downloads

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#34]
A progress bar for paginated loading would be a nice features to add.

There are many existing packages for this listed on [this stackExchange question](https://stackoverflow.com/questions/3160699/python-progress-bar). I would suggest we use one that is well maintained, popular, and uses only plain text.

If we would rather code our own, I like [this solution](https://stackoverflow.com/a/34482761/1483986) as a starting point.

**Comment by ayushanand18** [comment]
I think rather than additional dependencies which the user might need to install, we could use the latter solution that you suggested. I did an initial work and could reproduce it by just adding 3 lines of code to our existing code base.

Here are the edits I made:
```
out  = obis_GET(url,args,'application/json; charset=utf-8', **kwargs)
    size = out["total"] if not size else size # if the user has set some size or else we fetch all the records
    for i in range(5000,size+1,5000):
        if args["size"]!=0: # this condition is to make sure that we set the `after` parameter when fetching subsequent records only, and first batch gets fetched correctly without this `after` parameter
            args['after'] = res["results"][4999]['id']
        args['size'] = 5000
        print("{}[{}{}] {}/{}".format("Fetching: ", "█"*int((i-1)*100/size), "."*(100-int((i+1)*100/size)), i, size), end='\r', file=sys.stdout, flush=True)      # introduced this line
        res=obis_GET(url, args, 'application/json; charset=utf-8', **kwargs)
        out["results"]+=res["results"]
    args["size"] = size%5000 # we have already fetched records as a set of 5000 records each time, now we need to get remaining records from the total
    print("{}[{}{}] {}/{}".format("Fetching: ", "█"*100, "."*0, size, size), end='\r', file=sys.stdout, flush=True)      # introduced this line
    res=obis_GET(url, args, 'application/json; charset=utf-8', **kwargs)
    out["results"]+=res["results"]
    print("\nFetched {} records.".format(size))          # introduced this line
```

Here's the output:
```
Fetching: [████████████████████████████████████████████████████████████████████████████████████████████████████] 20972/20972
Fetched 20972 records.
```

**Comment by ayushanand18** [comment]
Just a point I'd like to make to this thread. The function is fetching huge amount of data, considering this if we implement an animated progress bar (as seen in the StackOverflow solutions) maybe from some module we could add up both dependencies as well as another degree to the already polynomial time complexity. Although, this additional time complexity is less significant for 1 or 2 fetches, it becomes significant when using this module for larger data exploration, which is more concerning to me. Personally, I consider time complexity an important metric when building a function or an algorithm.

**Comment by ayushanand18** [comment]
It is indeed true that network speed will always be the bottleneck (I have myself experienced it from the little experience I have gained using pyobis). But I feel sending multiple asynchronous requests might have some unexpected results, since each subsequent request depends on the previous one for the `after` parameter to fetch subsequent records. I am not sure I might be wrong here.

**Comment by 7yl4r** [comment]
Ah. That is a good point. It would be big undertaking to parrallelize. We could divide a query into multiple sub-queries spatially, temporally, or other ways... But it sounds like quite a headache. We are probably over-engineering this.

**Comment by ayushanand18** [comment]
Truly seconded.
