### ISSUE TITLE
/docs/ directory update (or remove?)

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#40]
`/docs/` looks to contain sphinx documentation. I am not familiar with building documentation like this. Can we add the docs build to a github action? Should we update to another tooling?

**Comment by MathewBiddle** [comment]
Maybe move from readthedocs to GH-Pages?

**Comment by ocefpaf** [comment]
> I am not familiar with building documentation like this. Can we add the docs build to a github action? Should we update to another tooling?

GHA for this is OK IMO. I'll send a PR to get it started so @ayushanand18 can focus on the documentation content instead.

**Comment by ocefpaf** [comment]
Done in #43
