### ISSUE TITLE
Maintenance and pyobis future 

### ISSUE THREAD

**Issue by ocefpaf** [iobis/pyobis#5]
Hi @sckott, are you still interested in maintaining pyobis? There is a growing community of Pythonistas that are using OBIS and would like to update and curate this package. Would you be interested in adding more committers and/or moving it to another organization?

**Comment by 7yl4r** [comment]
👋 I am one of those pythonistas willing to use, PR, and maintain this too. Also I can vouch for @ocefpaf's trustworthiness, technical skill, and general awesomeness.

**Comment by MathewBiddle** [comment]
👋 Me too! :)

**Comment by sckott** [comment]
hello all. thanks for the issue. i think it's been long enough to prove i don't have time to work on this :) And it would be 100x better if folks work on this that actually work in the domain area of the data in question. So where should i transfer the repo?

**Comment by pieterprovoost** [comment]
Great to hear that there's so much interest in the package. If that works for you all I'm happy to host the package at https://github.com/iobis and give you maintainer access.

**Comment by MathewBiddle** [comment]
That sounds good to me. @ocefpaf and @7yl4r, you okay with that?

**Comment by ocefpaf** [comment]
> That sounds good to me. @ocefpaf and @7yl4r, you okay with that?

Sounds good! Thanks @pieterprovoost and @sckott!

Having @7yl4r and myself with maintainer privileges would be enough IMO. There are very few things we'll need adim privileges and we can set those up together later and only once. (Like doc/package publication via GitHub Actions.)

We, IOOS, are planning on applying to Google Summer of Code and hopefully we can get a student to help us update to the latest OBIS API.

**Comment by sckott** [comment]
@pieterprovoost i've invited you to this repo, once you accept try transferring. i may have to bump privileges after you accept the invite

**Comment by pieterprovoost** [comment]
Thanks @sckott, I have accepted but don't have access to settings yet.

**Comment by sckott** [comment]
Looks like I can't give you adequate permissions to transfer the repo. I think you need to add to me iobis org and then i can transfer - then you can remove me from iobis after the transfer.

**Comment by sckott** [comment]
Okay, done!

@pieterprovoost remove me from your org whenever now. 

Let me know if you have any questions. 

Feel free to make any and all changes.

**Comment by pieterprovoost** [comment]
Done, thanks for all the great work!

**Comment by ocefpaf** [comment]
Let;s close this one for now. Thanks @pieterprovoost and @sckott for the quick response!
