### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MathewBiddle** [iobis/pyobis#63]
The docs are out of date https://pyobis.readthedocs.io/en/latest/

We should update them before GSoC ends.

**Comment by 7yl4r** [comment]
* gh-pages page should be working soon: https://iobis.github.io/pyobis
* https://pyobis.readthedocs.io/ cannot be updated easily
* pypi cannot be used until #44 is merged

**Comment by MathewBiddle** [comment]
I suggest we remove references to readthedocs for now and then look into how we can delete the site.
