### ISSUE TITLE
Document units and direction for use of depth search parameters

### ISSUE THREAD

**Issue by MathewBiddle** [iobis/pyobis#68]
If I wanted to do an occurrence search including a filter by depth. The docs don't currently tell me:
1. What units should I use?
2. What direction are we using?

For example, if I wanted to search between 10 and 50 meters depth, should I use:
`start_depth = -10`
`end_depth = -50`

Please update the docs to describe this. 

To share some information, the [Climate and Forecast conventions](https://cfconventions.org/) is what made me think of this nuance. The guidance is to specifically include `units` and `direction` with [vertical coordinates](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#vertical-coordinate). I don't think we need to handle conversions in the code, but we should be documenting what the expectation is.

**Comment by MathewBiddle** [comment]
I think the obis api assumes `depth` is a negative value. So you supply a positive number. In my example above, the options would be:
`start_depth=10`
`end_depth=50`

**Comment by MathewBiddle** [comment]
@ayushanand18 please check into this depth issue. I think there is a bug

**Comment by ayushanand18** [comment]
Thank you so much @MathewBiddle! that's an interesting insight. I agree that all physical quantities we will be using as parameters must be documented. Indeed, OBIS already treats depth as negative quantities, so we need to supply magnitudes of depth in meters. I will update the docstrings everywhere.
