### ISSUE TITLE
create conda-forge release 

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#71]
in addition to #17, we can publish to conda-forge. We just need to find or write a suitable github action.

**Comment by 7yl4r** [comment]
@ocefpaf : do you have some recommendation or boilerplate we can use here?

**Comment by ocefpaf** [comment]
When we have the PyPI release we can create a recipe with grayskull:

```
grayskull pypi --strict-conda-forge pyobis
```

and submit a PR to https://github.com/conda-forge/staged-recipes.

If we cannot get access to the PyPI namespace we can still create a conda-forge package from a github tag.

**Comment by MathewBiddle** [comment]
We're on pypi now 😉

**Comment by MathewBiddle** [comment]
How can we publish on conda-forge? @ocefpaf @7yl4r ?

**Comment by MathewBiddle** [comment]
oh Nice! Let's update the README.

**Comment by ocefpaf** [comment]
> oh Nice! Let's update the README.

@ayushanand18 that can be your 3rd PR towards hacktoberfest. Do you want to give it a go?

**Comment by ayushanand18** [comment]
> @ayushanand18 that can be your 3rd PR towards hacktoberfest. Do you want to give it a go?

I'm ready to take it. But fortunately or unfortunately, I opened the other two PRs on Sept 30, UTC 12:15. Practically that wasn't 1st Oct anywhere on Earth and so they didn't get counted.

**Comment by ocefpaf** [comment]
> I opened the other two PRs on Sept 30, UTC 12:15.

According to their rules it should. But don't worry. I have another adjustment to the README that you can make and get you closer to the goal.

**Comment by ayushanand18** [comment]
> According to their rules it should. But don't worry. I have another adjustment to the README that you can make and get you closer to the goal.

Thank you so much :) At the end of the day my goal is to make this project better with each commit and push.

**Comment by 7yl4r** [comment]
let's put a conda-forge button in the readme ([the one from here](https://github.com/conda-forge/pyobis-feedstock#current-release-info) and close this issue out. :partying_face:
