### ISSUE TITLE
Getting "null" mof value through /occurrence resource in the new OBIS API v3

### ISSUE THREAD

**Issue by ayushanand18** [iobis/pyobis#9]
Could you please help me out? While trying out the OBIS API v3 on Swagger, I get the mof value as *null every time I iter through the /occurrence resource. I am also attaching a screenshot for your reference.

Thank you for your time!

![image](https://user-images.githubusercontent.com/36472216/159647507-a6281636-a2c5-4370-a87a-f00f54862dbc.png)

**Comment by ayushanand18** [comment]
Thank you so much @pieterprovoost, this resolves my issue. I had tried for `Mola mola` which perhaps had no mof records as in here: https://api.obis.org/v3/occurrence?scientificname=Mola%20mola&mof=true. I now conclude that mof data may or may not exist for a species.

**But I have a doubt, what exactly do we mean by the statement "making mof response more efficient", it's already an array with the required keys?**

Thank you once again for helping me out!

PS. I got this array as mof response it still has some null values, this might be due to missing data I suppose.
![image](https://user-images.githubusercontent.com/36472216/159690101-dce3e3ed-47fb-4978-afa6-33dc551342fd.png)

**Comment by pieterprovoost** [comment]
@ayushanand18 Not sure where that statement is from?

Regarding the `mof` field, I'm still not sure why in some cases it's absent while in other cases it's present and `null`. So for now it's best to account for both. I'll also look into removing the `null` values from the MeasurementOrFact record, these are missing data indeed.

**Comment by ayushanand18** [comment]
Thanks @pieterprovoost, this was about one of the expected outcomes for GSoC 2022 [Link: [https://github.com/ioos/gsoc/issues/15#issue-1138800706](https://github.com/ioos/gsoc/issues/15#issue-1138800706)]. Thank you so much for the swift replies 😊

PS. If this API is Open Source I will feel honored to contribute to IOOS.

**Comment by MathewBiddle** [comment]
Adding this here to clarify why comment, will probably need a new ticket and more discussion.

@ayushanand18 in regards to my statement "making mof response more efficient", I was thinking about how we can streamline the mof response when using this python package. As it currently stands, when requesting the mof response, it comes back as a list of dictionaries for each occurrence (see below snippet and screenshot). 

What I was hoping we could do is write a module that translates that list of dictionaries into a pandas DataFrame, or at least something more manageable to work with. I'm trying to avoid having to write a loop that pulls all the mof data out for each occurrence. I'm not sure what that might look like (or if it's doable), so I'll leave the solution up to you to think about for this project. 


```
"mof":[{"measurementDeterminedBy":null,"measurementAccuracy":null,"measurementValue":"3","measurementRemarks":null,"measurementValueID":null,"level":0,"occurrenceID":"RSMP_RSMP_A_0505_Baseline_62622","measurementUnit":null,"measurementDeterminedDate":null,"measurementType":"individualCount","measurementUnitID":null,"measurementTypeID":"http://vocab.nerc.ac.uk/collection/P01/current/OCOUNT01/","measurementID":null,"measurementMethod":null},{"measurementDeterminedBy":null,"measurementAccuracy":null,"measurementValue":"0.1m2 Hamon grab","measurementRemarks":null,"measurementValueID":"http://vocab.nerc.ac.uk/collection/L22/current/TOOL0961/","level":1,"occurrenceID":null,"measurementUnit":null,"measurementDeterminedDate":null,"measurementType":"Sampling instrument name","measurementUnitID":null,"measurementTypeID":"http://vocab.nerc.ac.uk/collection/Q01/current/Q0100002/","measurementID":null,"measurementMethod":null}
```

![image](https://user-images.githubusercontent.com/8480023/160123676-a9aab117-f383-4b1d-bd43-f260ba836925.png)

**Comment by pieterprovoost** [comment]
@MathewBiddle I think this should do the trick? You'll need to specify which columns from the occurrence record you want to keep.

```python
import requests
import pandas as pd

response = requests.get("https://api.obis.org/occurrence?scientificname=Abra&mof=true&hasextensions=MeasurementOrFact")
results = response.json()["results"]

pd.io.json.json_normalize(results, "mof", ["scientificName", "eventDate"])
```

This is how it works in robis: https://github.com/iobis/robis/blob/master/R/util.R#L153

**Comment by MathewBiddle** [comment]
@pieterprovoost I learn something new everyday :) 
I didn't know about this trick with pandas `pd.io.json.json_normalize()` That does exactly what I was after. 

Would it be worth building that into the pyobis package? Similar to robis?

**Comment by pieterprovoost** [comment]
Probably. The idea in robis is that you first get a dataframe with the nested MeasurementOrFact records, and then optionally use the utility function to unnest the extension records. It's a utility function because in R that operation is more than just a one-liner. For pyobis I see a number of options:

- Provide a utility function that takes a dataframe and extracts the extension records (probably involves converting back to a list of dicts before using `json_normalize()`, not sure)
- Assume that users can figure that out by themselves
- Add an option to the base occurrence funcion to unnest the extension records right after fetching the occurrences

Not sure what's best, maybe the first option?

**Comment by ayushanand18** [comment]
@MathewBiddle @pieterprovoost Just a simple doubt, why do we mention GBIF in the pyobis package description. 

I know both OBIS and GBIF are intensely collaborating on the marine biodiversity data sphere, and there are multi-year data transfer agreements. Almost all OBIS nodes are listed in GBIF, and OBIS is their primary marine data source but couldn't get the fact that we are still reaching out to the OBIS API through this package at the end of the day. `robis` too mentions as "Client for OBIS". I have been researching it for the last 2 days, but still couldn't get this. 

I would deeply appreciate your help in this regard. Thanks in advance!

**Comment by pieterprovoost** [comment]
@ayushanand18 That seems to be a mistake, will need fixing at https://github.com/iobis/pyobis/blob/master/setup.py#L25

**Comment by ayushanand18** [comment]
Noted. Thanks a ton @pieterprovoost :)
