### ISSUE TITLE
incomplete fetch of checklist from `/checklist` endpoint

### ISSUE THREAD

**Issue by ayushanand18** [iobis/pyobis#93]
## Overview
When we try to generate an OBIS checklist using `pyobis.checklist` -> `list()` function, then it returns a checklist of size at max 10. This behavior is due to the fact that OBIS API returns by default returns a list of 10 records only in a query.
To fetch subsequent records, we need to pass a `skip` parameter to skip the number of records already fetched.

For example, let us look at this request
```console
https://api.obis.org/v3/checklist?size=10&skip=10&taxonid=1363
```
It fetches subsequent 10 records after first 10 have been fetched. 

## To reciprocate
Run
```python
from pyobis.checklist import ChecklistQuery
ChecklistQuery().list(taxonid=1363)["total"] # total records
len(ChecklistQuery().list(taxonid=1363)["results"]) # total fetched
```

**Note:** This is not something mentioned in the documentation, and I got this insight thanks to `OBIS Mapper`.

**Comment by ayushanand18** [comment]
We need to include a pagination process similar to `occurrences.search` here also. I'm writing a patch for this.

**Comment by ayushanand18** [comment]
An interesting finding, although I couldn't understand it. I queried checklist for `taxonid 1363`. The total was showing `2140` yet when I run this query I get zero results.
```console
https://api.obis.org/v3/checklist?taxonid=1363&skip=2129&size=5000
```
output
```json
{"total":2140,"results":[]}
```

Something weird and outside my understanding. Please help.

**Comment by 7yl4r** [comment]
I wonder if this is because [Dorylaimina](https://www.marinespecies.org/aphia.php?p=taxdetails&id=458802) is an Order. The total could be a count of species within the order.

@pieterprovoost : can you shed some light on this?

**Comment by ayushanand18** [comment]
Noted, Thanks @pieterprovoost for the info!
